#%RAML 1.0
title: appollo-tablets 
baseUri: http://appollo-tablets/api
/appollo:
  get:
    description: retrive the data from target systems
    responses:
      200:
        body:
          application/json:
            example: !include examples/create.json
  post:
    description: create data from target systems
    body:
      application/json:
        example: !include examples/create.json
    responses:
      201:
        body:
          application/json:
            example: !include examples/response.json
              
          
              